prepend_path( "PATH",           pathJoin("/work2/00434/eijkhout/swig/installation-4.1.1-clx-gcc9","bin")   )
setenv( "LMOD_SWIG_BIN",     pathJoin("/work2/00434/eijkhout/swig/installation-4.1.1-clx-gcc9","bin")   )
setenv( "TACC_SWIG_BIN",     pathJoin("/work2/00434/eijkhout/swig/installation-4.1.1-clx-gcc9","bin")   )
prepend_path( "LD_LIBRARY_PATH",pathJoin("/work2/00434/eijkhout/swig/installation-4.1.1-clx-gcc9","lib")   )
setenv( "LMOD_SWIG_DIR",     "/work2/00434/eijkhout/swig/installation-4.1.1-clx-gcc9"                     )
setenv( "LMOD_SWIG_INC",     pathJoin("/work2/00434/eijkhout/swig/installation-4.1.1-clx-gcc9","include")   )
setenv( "LMOD_SWIG_LIB",     pathJoin("/work2/00434/eijkhout/swig/installation-4.1.1-clx-gcc9","lib")   )
setenv( "TACC_SWIG_DIR",     "/work2/00434/eijkhout/swig/installation-4.1.1-clx-gcc9"                     )
setenv( "TACC_SWIG_INC",     pathJoin("/work2/00434/eijkhout/swig/installation-4.1.1-clx-gcc9","include")   )
setenv( "TACC_SWIG_LIB",     pathJoin("/work2/00434/eijkhout/swig/installation-4.1.1-clx-gcc9","lib")   )
prepend_path( "CMAKE_PREFIX_PATH", "/work2/00434/eijkhout/swig/installation-4.1.1-clx-gcc9" )
