prepend_path(    "PATH",           pathJoin("/work2/00434/eijkhout/gklib/installation-git-clx-gcc-","bin")   )
prepend_path(    "LD_LIBRARY_PATH",pathJoin("/work2/00434/eijkhout/gklib/installation-git-clx-gcc-","lib")   )
setenv( "TACC_GKLIB_DIR",     "/work2/00434/eijkhout/gklib/installation-git-clx-gcc-"                     )
setenv( "TACC_GKLIB_INC",     pathJoin("/work2/00434/eijkhout/gklib/installation-git-clx-gcc-","include")   )
setenv( "TACC_GKLIB_LIB",     pathJoin("/work2/00434/eijkhout/gklib/installation-git-clx-gcc-","lib")   )
setenv( "TACC_GKLIB_DIR",     "/work2/00434/eijkhout/gklib/installation-git-clx-gcc-"                     )
setenv( "TACC_GKLIB_INC",     pathJoin("/work2/00434/eijkhout/gklib/installation-git-clx-gcc-","include")   )
setenv( "TACC_GKLIB_LIB",     pathJoin("/work2/00434/eijkhout/gklib/installation-git-clx-gcc-","lib")   )
setenv( "TACC_GKLIB_BIN",     pathJoin("/work2/00434/eijkhout/gklib/installation-git-clx-gcc-","bin")   )
