prepend_path( "PATH",           pathJoin("/work2/00434/eijkhout/peridigm/installation-git-clx-intel-impi","bin")   )
setenv( "TACC_PERIDIGM_BIN",     pathJoin("/work2/00434/eijkhout/peridigm/installation-git-clx-intel-impi","bin")   )
setenv( "TACC_PERIDIGM_BIN",     pathJoin("/work2/00434/eijkhout/peridigm/installation-git-clx-intel-impi","bin")   )
prepend_path( "LD_LIBRARY_PATH",pathJoin("/work2/00434/eijkhout/peridigm/installation-git-clx-intel-impi","lib")   )
setenv( "TACC_PERIDIGM_DIR",     "/work2/00434/eijkhout/peridigm/installation-git-clx-intel-impi"                     )
setenv( "TACC_PERIDIGM_INC",     pathJoin("/work2/00434/eijkhout/peridigm/installation-git-clx-intel-impi","include")   )
setenv( "TACC_PERIDIGM_LIB",     pathJoin("/work2/00434/eijkhout/peridigm/installation-git-clx-intel-impi","lib")   )
setenv( "TACC_PERIDIGM_DIR",     "/work2/00434/eijkhout/peridigm/installation-git-clx-intel-impi"                     )
setenv( "TACC_PERIDIGM_INC",     pathJoin("/work2/00434/eijkhout/peridigm/installation-git-clx-intel-impi","include")   )
setenv( "TACC_PERIDIGM_LIB",     pathJoin("/work2/00434/eijkhout/peridigm/installation-git-clx-intel-impi","lib")   )
