prepend_path( "PATH",           pathJoin("/work2/00434/eijkhout/netcdf/installation-4.9.2-clx-intel-impi","bin")   )
setenv( "TACC_NETCDF_BIN",     pathJoin("/work2/00434/eijkhout/netcdf/installation-4.9.2-clx-intel-impi","bin")   )
setenv( "TACC_NETCDF_BIN",     pathJoin("/work2/00434/eijkhout/netcdf/installation-4.9.2-clx-intel-impi","bin")   )
prepend_path( "LD_LIBRARY_PATH",pathJoin("/work2/00434/eijkhout/netcdf/installation-4.9.2-clx-intel-impi","lib")   )
setenv( "TACC_NETCDF_DIR",     "/work2/00434/eijkhout/netcdf/installation-4.9.2-clx-intel-impi"                     )
setenv( "TACC_NETCDF_INC",     pathJoin("/work2/00434/eijkhout/netcdf/installation-4.9.2-clx-intel-impi","include")   )
setenv( "TACC_NETCDF_LIB",     pathJoin("/work2/00434/eijkhout/netcdf/installation-4.9.2-clx-intel-impi","lib")   )
setenv( "TACC_NETCDF_DIR",     "/work2/00434/eijkhout/netcdf/installation-4.9.2-clx-intel-impi"                     )
setenv( "TACC_NETCDF_INC",     pathJoin("/work2/00434/eijkhout/netcdf/installation-4.9.2-clx-intel-impi","include")   )
setenv( "TACC_NETCDF_LIB",     pathJoin("/work2/00434/eijkhout/netcdf/installation-4.9.2-clx-intel-impi","lib")   )
