prepend_path(    "PATH",           pathJoin("/work2/00434/eijkhout/gklib/installation-git-clx-gcc-impi","bin")   )
prepend_path(    "LD_LIBRARY_PATH",pathJoin("/work2/00434/eijkhout/gklib/installation-git-clx-gcc-impi","lib")   )
setenv( "TACC_GKLIB_DIR",     "/work2/00434/eijkhout/gklib/installation-git-clx-gcc-impi"                     )
setenv( "TACC_GKLIB_INC",     pathJoin("/work2/00434/eijkhout/gklib/installation-git-clx-gcc-impi","include")   )
setenv( "TACC_GKLIB_LIB",     pathJoin("/work2/00434/eijkhout/gklib/installation-git-clx-gcc-impi","lib")   )
setenv( "TACC_GKLIB_DIR",     "/work2/00434/eijkhout/gklib/installation-git-clx-gcc-impi"                     )
setenv( "TACC_GKLIB_INC",     pathJoin("/work2/00434/eijkhout/gklib/installation-git-clx-gcc-impi","include")   )
setenv( "TACC_GKLIB_LIB",     pathJoin("/work2/00434/eijkhout/gklib/installation-git-clx-gcc-impi","lib")   )
setenv( "TACC_GKLIB_BIN",     pathJoin("/work2/00434/eijkhout/gklib/installation-git-clx-gcc-impi","bin")   )
