prepend_path( "LD_LIBRARY_PATH",pathJoin("/work2/00434/eijkhout/gklib/installation-git-clx-intel-impi","lib")   )
setenv( "TACC_GKLIB_DIR",     "/work2/00434/eijkhout/gklib/installation-git-clx-intel-impi"                     )
setenv( "TACC_GKLIB_INC",     pathJoin("/work2/00434/eijkhout/gklib/installation-git-clx-intel-impi","include")   )
setenv( "TACC_GKLIB_LIB",     pathJoin("/work2/00434/eijkhout/gklib/installation-git-clx-intel-impi","lib")   )
setenv( "TACC_GKLIB_DIR",     "/work2/00434/eijkhout/gklib/installation-git-clx-intel-impi"                     )
setenv( "TACC_GKLIB_INC",     pathJoin("/work2/00434/eijkhout/gklib/installation-git-clx-intel-impi","include")   )
setenv( "TACC_GKLIB_LIB",     pathJoin("/work2/00434/eijkhout/gklib/installation-git-clx-intel-impi","lib")   )
