prepend_path( "PATH",           pathJoin("/work2/00434/eijkhout/gdal/installation-3.7.0-clx-gcc9","bin")   )
setenv( "LMOD_GDAL_BIN",     pathJoin("/work2/00434/eijkhout/gdal/installation-3.7.0-clx-gcc9","bin")   )
setenv( "TACC_GDAL_BIN",     pathJoin("/work2/00434/eijkhout/gdal/installation-3.7.0-clx-gcc9","bin")   )
prepend_path( "LD_LIBRARY_PATH",pathJoin("/work2/00434/eijkhout/gdal/installation-3.7.0-clx-gcc9","lib")   )
setenv( "LMOD_GDAL_DIR",     "/work2/00434/eijkhout/gdal/installation-3.7.0-clx-gcc9"                     )
setenv( "LMOD_GDAL_INC",     pathJoin("/work2/00434/eijkhout/gdal/installation-3.7.0-clx-gcc9","include")   )
setenv( "LMOD_GDAL_LIB",     pathJoin("/work2/00434/eijkhout/gdal/installation-3.7.0-clx-gcc9","lib")   )
setenv( "TACC_GDAL_DIR",     "/work2/00434/eijkhout/gdal/installation-3.7.0-clx-gcc9"                     )
setenv( "TACC_GDAL_INC",     pathJoin("/work2/00434/eijkhout/gdal/installation-3.7.0-clx-gcc9","include")   )
setenv( "TACC_GDAL_LIB",     pathJoin("/work2/00434/eijkhout/gdal/installation-3.7.0-clx-gcc9","lib")   )
prepend_path( "CMAKE_PREFIX_PATH", "/work2/00434/eijkhout/gdal/installation-3.7.0-clx-gcc9" )
