prepend_path( "PATH",           pathJoin("/work2/00434/eijkhout/hdf5/installation-1.14-clx-intel-impi","bin")   )
setenv( "TACC_HDF5_BIN",     pathJoin("/work2/00434/eijkhout/hdf5/installation-1.14-clx-intel-impi","bin")   )
setenv( "TACC_HDF5_BIN",     pathJoin("/work2/00434/eijkhout/hdf5/installation-1.14-clx-intel-impi","bin")   )
prepend_path( "LD_LIBRARY_PATH",pathJoin("/work2/00434/eijkhout/hdf5/installation-1.14-clx-intel-impi","lib")   )
setenv( "TACC_HDF5_DIR",     "/work2/00434/eijkhout/hdf5/installation-1.14-clx-intel-impi"                     )
setenv( "TACC_HDF5_INC",     pathJoin("/work2/00434/eijkhout/hdf5/installation-1.14-clx-intel-impi","include")   )
setenv( "TACC_HDF5_LIB",     pathJoin("/work2/00434/eijkhout/hdf5/installation-1.14-clx-intel-impi","lib")   )
setenv( "TACC_HDF5_DIR",     "/work2/00434/eijkhout/hdf5/installation-1.14-clx-intel-impi"                     )
setenv( "TACC_HDF5_INC",     pathJoin("/work2/00434/eijkhout/hdf5/installation-1.14-clx-intel-impi","include")   )
setenv( "TACC_HDF5_LIB",     pathJoin("/work2/00434/eijkhout/hdf5/installation-1.14-clx-intel-impi","lib")   )
prepend_path( "PKG_CONFIG_PATH", pathJoin( "/work2/00434/eijkhout/hdf5/installation-1.14-clx-intel-impi","lib/pkgconfig" ) )
