prepend_path( "LD_LIBRARY_PATH",pathJoin("/work2/00434/eijkhout/cxxopts/installation-3.1.1-clx-intel22","lib")   )
setenv( "LMOD_CXXOPTS_DIR",     "/work2/00434/eijkhout/cxxopts/installation-3.1.1-clx-intel22"                     )
setenv( "LMOD_CXXOPTS_INC",     pathJoin("/work2/00434/eijkhout/cxxopts/installation-3.1.1-clx-intel22","include")   )
setenv( "LMOD_CXXOPTS_LIB",     pathJoin("/work2/00434/eijkhout/cxxopts/installation-3.1.1-clx-intel22","lib")   )
setenv( "TACC_CXXOPTS_DIR",     "/work2/00434/eijkhout/cxxopts/installation-3.1.1-clx-intel22"                     )
setenv( "TACC_CXXOPTS_INC",     pathJoin("/work2/00434/eijkhout/cxxopts/installation-3.1.1-clx-intel22","include")   )
setenv( "TACC_CXXOPTS_LIB",     pathJoin("/work2/00434/eijkhout/cxxopts/installation-3.1.1-clx-intel22","lib")   )
prepend_path( "PKG_CONFIG_PATH", pathJoin( "/work2/00434/eijkhout/cxxopts/installation-3.1.1-clx-intel22","lib64/pkgconfig" ) )
