prepend_path( "LD_LIBRARY_PATH",pathJoin("/work2/00434/eijkhout/cfitsio/installation-4.2.0-clx-intel23","lib")   )
setenv( "LMOD_CFITSIO_DIR",     "/work2/00434/eijkhout/cfitsio/installation-4.2.0-clx-intel23"                     )
setenv( "LMOD_CFITSIO_INC",     pathJoin("/work2/00434/eijkhout/cfitsio/installation-4.2.0-clx-intel23","include")   )
setenv( "LMOD_CFITSIO_LIB",     pathJoin("/work2/00434/eijkhout/cfitsio/installation-4.2.0-clx-intel23","lib")   )
setenv( "TACC_CFITSIO_DIR",     "/work2/00434/eijkhout/cfitsio/installation-4.2.0-clx-intel23"                     )
setenv( "TACC_CFITSIO_INC",     pathJoin("/work2/00434/eijkhout/cfitsio/installation-4.2.0-clx-intel23","include")   )
setenv( "TACC_CFITSIO_LIB",     pathJoin("/work2/00434/eijkhout/cfitsio/installation-4.2.0-clx-intel23","lib")   )
prepend_path( "PKG_CONFIG_PATH", pathJoin( "/work2/00434/eijkhout/cfitsio/installation-4.2.0-clx-intel23","lib/pkgconfig" ) )
prepend_path( "CMAKE_PREFIX_PATH", "/work2/00434/eijkhout/cfitsio/installation-4.2.0-clx-intel23" )
