prepend_path( "LD_LIBRARY_PATH",pathJoin("/work2/00434/eijkhout/parmetis/installation-git-clx-intel19-impi","lib")   )
setenv( "LMOD_PARMETIS_DIR",     "/work2/00434/eijkhout/parmetis/installation-git-clx-intel19-impi"                     )
setenv( "LMOD_PARMETIS_INC",     pathJoin("/work2/00434/eijkhout/parmetis/installation-git-clx-intel19-impi","include")   )
setenv( "LMOD_PARMETIS_LIB",     pathJoin("/work2/00434/eijkhout/parmetis/installation-git-clx-intel19-impi","lib")   )
setenv( "TACC_PARMETIS_DIR",     "/work2/00434/eijkhout/parmetis/installation-git-clx-intel19-impi"                     )
setenv( "TACC_PARMETIS_INC",     pathJoin("/work2/00434/eijkhout/parmetis/installation-git-clx-intel19-impi","include")   )
setenv( "TACC_PARMETIS_LIB",     pathJoin("/work2/00434/eijkhout/parmetis/installation-git-clx-intel19-impi","lib")   )
prepend_path( "CMAKE_PREFIX_PATH", "/work2/00434/eijkhout/parmetis/installation-git-clx-intel19-impi" )
