prepend_path(    "PATH",           pathJoin("/work2/00434/eijkhout/metis/installation-git-clx-intel-impi","bin")   )
prepend_path(    "LD_LIBRARY_PATH",pathJoin("/work2/00434/eijkhout/metis/installation-git-clx-intel-impi","lib")   )
setenv( "TACC_METIS_DIR",     "/work2/00434/eijkhout/metis/installation-git-clx-intel-impi"                     )
setenv( "TACC_METIS_INC",     pathJoin("/work2/00434/eijkhout/metis/installation-git-clx-intel-impi","include")   )
setenv( "TACC_METIS_LIB",     pathJoin("/work2/00434/eijkhout/metis/installation-git-clx-intel-impi","lib")   )
setenv( "TACC_METIS_DIR",     "/work2/00434/eijkhout/metis/installation-git-clx-intel-impi"                     )
setenv( "TACC_METIS_INC",     pathJoin("/work2/00434/eijkhout/metis/installation-git-clx-intel-impi","include")   )
setenv( "TACC_METIS_LIB",     pathJoin("/work2/00434/eijkhout/metis/installation-git-clx-intel-impi","lib")   )
setenv( "TACC_METIS_BIN",     pathJoin("/work2/00434/eijkhout/metis/installation-git-clx-intel-impi","bin")   )
